services:
  successweb:
    image: ghcr.io/karenbaldryan/successweb:latest
    container_name: successweb
    restart: unless-stopped
    ports:
      - "80"
    networks:
      playarena2: {}
networks:
  playarena2:
    external: true